# Site
name: 'Dohela'
description: 'Eski bir efsanenin yarım kalmış hikayesi...'
logo: '/assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'root@dohela.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    dohela:
      name:           dohela
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Merhaba,ben dohela web güvenliği ve bir çok vuln yöntemleriyle uğaşıyorum."
      email:          root@dohela
      twitter:        https://twitter.com/spydohela

  
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]